# Generated by Django 4.2.6 on 2023-10-28 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("archive", "0002_chatarchive_prompt_chatarchive_res_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatarchive",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ArchiveToUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
